export interface Transaction {
  transaction_id: string;
  date_start: string;
  date_start_new: string;
  date_close: string;
  status: string;
  guests_count: string;
  discount: string;
  bonus: string;
  pay_type: string;
  payed_bonus: string;
  payed_card: string;
  payed_cash: string;
  payed_sum: string;
  payed_cert: string;
  payed_third_party: string;
  payed_card_type: string;
  payed_ewallet: string;
  round_sum: string;
  tip_sum: string;
  tips_card: string;
  tips_cash: string;
  sum: string;
  tax_sum: string;
  payment_method_id: string;
  spot_id: string;
  table_id: string;
  name?: string;
  user_id: string;
  client_id: string;
  card_string: string;
  transaction_comment?: string | null;
  reason?: string;
  print_fiscal: string;
  total_profit: string;
  total_profit_netto: string;
  table_name: string;
  client_firstname?: string | null;
  client_lastname?: string | null;
  date_close_date?: string;
  service_mode: string;
  processing_status: string;
  client_phone?: string | null;
  auto_accept: boolean;
  application_id?: string | null;
}
